### ISSUE TITLE
Tacos: Life, liberty and the pursuit of more tacos.

### ISSUE THREAD

**Issue by iamcarrico** [una/ama#12]
Hey @una, long-time listener— first time caller. I just wanted to say before I asked a question that I am a HUGE fan. I think the work you are doing in open source is hellah-rad. 

![I fill these in, I dont think people read them](http://25.media.tumblr.com/9acad1b0929a2e5095625308a206b2a2/tumblr_mfp42nVaTR1r41qo7o1_500.gif)

Anyway, my question is incredibly controversial— and I am sorry for that. But... what are your favorite breakfast tacos? 

![TACOS? Yes please](https://becomingmrsmccully.files.wordpress.com/2014/10/tacos.gif)

**Comment by iamcarrico** [comment]
![I can add so many more of these](http://2.media.collegehumor.cvcdn.com/64/14/cc6058e0106e00f9342fe73b5d8a60df-taco9.gif)

**Comment by iamcarrico** [comment]
![okay, just this last one... I swear](https://33.media.tumblr.com/7013c26f936cff3a6133480e07fba67b/tumblr_mll7ztQZaf1r0y8j6o1_500.gif)

**Comment by una** [comment]
![taco](https://cloud.githubusercontent.com/assets/1693164/8863113/a1c10756-314a-11e5-9d92-995a7bec441d.gif)

I'm a Taco Deli Fangurl <3
