### ISSUE TITLE
What was your most soul-crushing conference proposal rejection?

### ISSUE THREAD

**Issue by nebrius** [una/ama#13]
If you're anything like me, I'm sure you've had that one proposal you were super pscyhed about that you had a good feeling about that got rejected :)

**Comment by una** [comment]
I really wanted to (still want to) give a talk about this super cool goals repo/workflow thing I've been doing on the Githubs (its made a huge difference in my life), and extend that to using GitHub beyond code (people have done some cool things!) or other productivity life hacks. But nobody wanted to see it :( Maybe next year. I submitted the talk to SXSW :) It's called "A Year in the Open" _fingers crossed_

**Comment by nebrius** [comment]
Oh that does sound cool, I would definitely listen! The organizer in me does see it being a little tricky to slot in to a flow of talks for a really technical conference. I think a conference that would accept it says a lot about the experience they're trying to create :)
