### ISSUE TITLE
Other hobbies?

### ISSUE THREAD

**Issue by ChrisMissal** [una/ama#14]
What other hobbies or activities do you love that aren't tech related?

**Comment by una** [comment]
So many! :smile: 

Firstly, I love to travel. So much. I really want to write a travel book. 

I also love illustration (by hand) and [drawing](http://sketchbook.unakravets.com), painting, calligraphy, and hand-lettering. Basically I am super crafty and just like to make things really (like cards) and I used to be on the Youtube's for nail art :nail_care: 

Here are some pics from my [Instagram](http://instagram.com/unakravets):

<img width="640" alt="screen shot 2015-07-23 at 3 41 29 pm" src="https://cloud.githubusercontent.com/assets/1693164/8863984/16ab8f30-3152-11e5-8270-7d798b305bea.png">
<img width="639" alt="screen shot 2015-07-23 at 3 41 42 pm" src="https://cloud.githubusercontent.com/assets/1693164/8863983/16ab59b6-3152-11e5-9e83-241e08cb430c.png">
<img width="638" alt="screen shot 2015-07-23 at 3 41 58 pm" src="https://cloud.githubusercontent.com/assets/1693164/8863985/16ac0f00-3152-11e5-879e-60e8c06350da.png">
