### ISSUE TITLE
What are you looking at in your profile picture?

### ISSUE THREAD

**Issue by sindresorhus** [una/ama#16]
![image](https://cloud.githubusercontent.com/assets/170270/8896498/dc36f498-33fe-11e5-91f0-affb077b2eb5.png)

**Comment by una** [comment]
I was at a coffee shop with a bunch of people after CSS Conf AU and was just sitting with my hands like that at breakfast. Karolina Szczur, who takes amazing portraits, was there. I joke-posed for a second, and she actually liked it so she told me to do it again. So I wasn't looking at anything, her photo skillz are just magical.
