### ISSUE TITLE
What's your favorite travel destination and why?

### ISSUE THREAD

**Issue by sindresorhus** [una/ama#18]

**Comment by una** [comment]
Anywhere I haven't yet been :) As of now, Croatia and Montenegro (Southeastern Europe in general) has been my favorite. It's SO stunning and I had a really awesome, unexpected adventure there. So to me it brings back wonderful memories and I would highly recommend those places to anyone.

![image](https://cloud.githubusercontent.com/assets/1693164/8897281/54fef7fa-33e0-11e5-98f8-2f7290b3207d.png)
Hvar, Croatia

![image](https://cloud.githubusercontent.com/assets/1693164/8897282/63181146-33e0-11e5-93cc-f8c5d12fed3c.png)
Kotor, Montenegro

![image](https://cloud.githubusercontent.com/assets/1693164/8897283/6814ba32-33e0-11e5-8c91-e674db8b1e63.png)
Kotor, Montenegro
