### ISSUE TITLE
Okay, so why did you almost consume flowers last night??

### ISSUE THREAD

**Issue by jglovier** [una/ama#19]
https://twitter.com/Una/status/630084108585185280

Both why almost, and why not?

**Comment by una** [comment]
Hahah they were in a drink. It was a _really_ good cocktail. Just came with a questionable garnish :stuck_out_tongue_winking_eye: 

I'm not sure they were edible.

**Comment by jglovier** [comment]
Ha! Definitely wouldn't have guessed a drink. Soup would have been my guess.

**Comment by jglovier** [comment]
Ooo after looking at the pic with that context, I can now see it was a drink lol. :blush:
