### ISSUE TITLE
What do you think about Spain?

### ISSUE THREAD

**Issue by aarroyoc** [una/ama#21]
How do people from outside Spain thinks about Spain? and How do you think about Spain?

**Comment by una** [comment]
I've only been to Barcelona for a few days but oh my gosh that city is SO beautiful! I didn't spend enough time there (its among the top 3 cities I really want to return to). Some of my favorite traditional artists (painters) come from Spain and the food is :heart:. Politically I'm neutral about the country :smile: it's a fantastic place and I definitely hope to make it back some day soon!
