### ISSUE TITLE
What are your favourite apps for productivity?

### ISSUE THREAD

**Issue by lborgav** [una/ama#23]
What apps do you use daily for managing tasks, to do lists, drafts ?

**Comment by una** [comment]
I love using [Self Control](https://selfcontrolapp.com/) when I find myself perusing Twitter too much. I also use [Pocket](https://getpocket.com/) for articles I want to read (they have a new TTS mode so I can listen to them! :heart: ). My to-do list is my [Goals Repo](https://github.com/una/personal-goals) and I access it in terminal. :smile:

**Comment by lborgav** [comment]
:smile:

**Comment by santhoshvai** [comment]
have you open-sourced your terminal app too? I want to shamelessly copy this to-do list way of working 😊

**Comment by una** [comment]
It's not really an app so much as a set of aliases --  which can be found here: http://github.com/una/dotfiles
