### ISSUE TITLE
What kind of music do you listen when you're designing?

### ISSUE THREAD

**Issue by ghost** [una/ama#24]
Well, my little secret is that I'm a pianist/musician. I'm not intended to spam you but I'll leave one of the songs I've played in the past. (Black keys by Frederic Chopin). I cheated on that one a bit, though.

https://soundcloud.com/spicymagpie/chopin-black-keys

Well, you wrote that your family was from Ukraine, and I always had the perception that Ukrainians have a gut for music, even if they are not interested in it. On the other hand, I always thought that music defines certain patterns on us that aren't easy to discover otherwise. Perhaps you can provide me with a list that can be an inspiration to finish my Website.

**Comment by una** [comment]
Hehe I listen to a wide variety of music. Currently, I have been _very_ into French electronica (specifically Stromae). My favorite part of a song is the lyrics and story, so I also like indie folk music that makes me feel transported to a place.

Here are a few of my up-to-date playlists:

https://open.spotify.com/user/1163733392/playlist/3gMt405B2WrHvZZBkwXO0V
https://open.spotify.com/user/1163733392/playlist/72EGvnFjzyvUFLkl8lBKva
https://open.spotify.com/user/1163733392/playlist/0rKfKKp4YnbZQlxBKinaVY
