### ISSUE TITLE
Advice for someone joining the tech field?

### ISSUE THREAD

**Issue by dideler** [una/ama#29]
Hey Una,

My partner (@katbow), who has a background in teaching natural sciences, has recently started learning to code. I'm pretty excited about this! She's started with CodeAcademy courses such as HTML, CSS, and JS and just yesterday did her first code kata on CodeWars. Her goal is to join a coding bootcamp in January.

My question is, do you have any advice or words of encouragement for when she inevitably reaches the dark desert of despair. Those moments when you question yourself and feel like an imposter, that maybe you should be switching career goals -- which I think every programmer has gone through.

![image](https://cloud.githubusercontent.com/assets/497458/10267572/1c035896-6a91-11e5-9fa5-274c4632b894.png)

P.S. I'm your 300th follower on GitHub, woohoo!

**Comment by una** [comment]
1. It's so awesome that she's coming from a science background!
2. Yay! Thank you for being my 300th follower!
3. Advice: desert of despair is real. But it isn't something that only happens at one period in your career. I constantly have those moments when I panic and think "I don't know what I'm doing." People who have been coding for 15 years still have those moments (especially with how quickly this industry changes). The best advice I could give is to realize that literally _everyone_ feels this way occasionally, look at your work from 6 months ago, and see how much you've improved. Also, when getting frustrated by a development problem, it often helps to take a step back and go to sleep and then attack it in the morning. 

Hope that helps!

**Comment by dideler** [comment]
Thanks Una for the solid advice :100:
