### ISSUE TITLE
How did you get your start in development?

### ISSUE THREAD

**Issue by jglovier** [una/ama#31]
Curious to know if you studied computer science in college? If so, or if not, did you start learning prior to college? I.e. what did your path to where you now look like at the beginning of your development journey?

**Comment by una** [comment]
I did study CS, but I don't think I got a ton out of my University's CS program -- I started out as a double major in Design and Computer Science and ended up dropping the CS major to a minor while finishing my Design Degree and doing a bunch of internships + self-teaching instead.

If you want the long story, I answered this in much more detail here: https://github.com/una/ama/issues/20

**Comment by jglovier** [comment]
> I answered this in much more detail here: #20

@una wow, thanks for sharing your experience. Your determination and perseverance in the face of adversity is inspiring, to say the least. Thanks for sticking with it, and being a valuable part to this community. :heart:

**Comment by jglovier** [comment]
Also, shout out to pixel dresses. :smile:

**Comment by una** [comment]
:smile: thanks for the question
