### ISSUE TITLE
What's the best way to get started with JS?

### ISSUE THREAD

**Issue by s1db** [una/ama#34]
Hello! I've been designing for a year now, I'm pretty fluent in HTML and CSS but I keep on getting intimidated by the syntax of JS. Could you recommend some resources for JS and were you intimated by JS when you started?

**Comment by una** [comment]
JavaScript is a huge world! And of course it's intimidating. I'm constantly in awe of all the things you can do with JavaScript.

The first thing is to understand programming concepts if you want to build anything significant with it. Architecture is key for a good fundamental understanding. Then, learning the syntax comes next. You learn the syntax by just practicing and making things. There are online resources like CodeSchool and Treehouse, and those are nice basics overviews, but you're going to want to just build things.

I really love the [YDKJS](https://github.com/getify/You-Dont-Know-JS) series for really understanding the language. It's an awesome series that really helped me understand the "why" of how it works.

Then, there are branches you can flow out to -- node.js is a server-side language that uses JS syntax which is really powerful. I would stay away from learning frameworks like React or Angular and focus more on concepts in the beginning (like the MVC model in general) until you have a need for the benefits of those frameworks.
