### ISSUE TITLE
How do you decide what makes a good talk.

### ISSUE THREAD

**Issue by Rchristiani** [una/ama#37]
When you are submitting a talk to a conference how do you decide what would make for an interesting talk? Stuff you are working on, or the direction the industry is going?

Thanks!

**Comment by una** [comment]
I think what makes a good talk is the intersection of what someone is interested in (the speaker) and what's new in tech. People love seeing that passion and a presentation on a new subject (things happening in the tech world) mixed with random fun facts and stories. Basically, I write as I learn, and eventually build a subject to present on. 

Look forward, experiment, and share :)
