### ISSUE TITLE
How do you beat procrastination?

### ISSUE THREAD

**Issue by santhoshvai** [una/ama#40]
You seem to have done a lot this year👍.  I would like to know the strategy that you use to beat procrastination.

**Comment by una** [comment]
First and foremost: lists.

Having a list of tasks makes me stick to them. And thats the #1 thing for productivity. Have you seen my [personal goals repo](http://github.com/una/personal-goals)?

Secondly: avoiding distractions.

I use Self Control to remove myself from Twitter and the like when I really need to get things done.
