### ISSUE TITLE
Text Editors Question :)

### ISSUE THREAD

**Issue by ghost** [una/ama#46]
Hey Una,

You're quite inspiring. I've really been stoked to use the `personal-goals` repo format that I saw on your GitHub, it's been fun.

Just curious, what editor do you use for editing markdown + what editor do you use for coding?

Hope you have fun in the NYC snow!

**Comment by una** [comment]
When writing a longer article, I use Sublime Text. If it's just small updates in my repo, I use vim :smile: [Here's my setup](http://github.com/una/dotfiles)
