### ISSUE TITLE
Thoughts on Daily Rituals Book?

### ISSUE THREAD

**Issue by ghost** [una/ama#47]
I just finished the Daily Rituals book as well. Did you like it?

I found it to be incredibly inspiring. Although, one thing that I took away from the book was just how many negative habits the famous artists, scientists, writers, and mathematicians use to fortify their deep work. They were mostly all addicted to either alcohol, cigars, cigarettes, or amphetamines. I found that to be really weird or just something I never thought about. 

I think if that book was written in 2090 about innovators in this current time, I would hope there are less destructive habits mentioned. I know Tim Ferriss and a few others talk about the idea that writers have some kind of implicit "demons" as he calls it, that push them to keep writing or creating. I wonder if that's a commonality amongst all creatives.

**Comment by una** [comment]
I thought the book was okay -- it didn't really teach me anything new and kind of made me realize how sad so many artist's lives were. I think yes, it takes something deeper than an "average" human to drive real innovation, and it was interesting to learn about their habits, but it made it seem like balance was impossible for most.

The one takeaway was that consistency is key. And I think balance is possible with consistency. They weren't _all_ crazy, and many had families and lives.
