### ISSUE TITLE
Where do you see yourself in 10 years?

### ISSUE THREAD

**Issue by mxstbr** [una/ama#48]
I think this is quite a hard question to answer (I know I couldn't answer it), but I'd be interested to know what your long term goals are.

You've "made it", in the sense that many people are interested in the things you create, you speak at conferences and are generally well known and liked. What are your next steps?

**Comment by una** [comment]
Haha what a great, and terrible question. I have absolutely no idea where I'll be in 10 years! Hopefully on my own yacht in charter using its wifi to do some work or write in a tropical place 😅. That's a nice little dream. I'll be 33 (woah. even thinking about being that age seems crazy to me right now!).

In terms of my professional life, I hope to have written a book by then and to be making significant contributions to the development community. In terms of my personal life, I'd love to have a family at some point. I can't even begin to sort out how this will work out with trying to balance a career, but some people make it work, right? I'd love to have a more significant impact in a larger community by 10 years from now. We will see I suppose! I really feel like with hard work and setting the right game plan, anything is possible!
