### ISSUE TITLE
Digital Ocean

### ISSUE THREAD

**Issue by jdorfman** [una/ama#50]
Hey Una,

Two parter: 
1. Did your move to DO meet or beat expectations?
2. As an Open Source developer, how does it benefit you working for them?

**Comment by una** [comment]
Hi Justin!
1. I think it meets expectation :) I heard a lot of great things about DO before joining and sort of had a slow process of asking a lot of questions and testing the waters before joining the team. Definitely glad I did!
2. I'm learning a lot right now -- just picked up Ember.js today/yesterday -- so thats been pretty cool. And there are always little PRs to be made here and there whenever you're new at something (i.e. along the process of learning I contributed a tiny bit to their docs). DO also is a big supporter of open source and has initiatives like Hacktoberfest which I love and am excited to see take hold.
