### ISSUE TITLE
How do you feel about the state of JS in 2016?

### ISSUE THREAD

**Issue by martindidiego** [una/ama#52]
Also what do you think JS (and its community) will be like 5 years from now?

**Comment by una** [comment]
OOoh interesting question! The state of JS in 2016 is pretty fragmented but I think thats a good thing. People are starting to build their own solutions and think ahead from the status quo.

On that note, 2016 is a lot less fragmented than 2015, with a lot of the major frameworks taking hints from one another (i.e. React building a CLI tool like Ember has, Angular 2.0 following some of the other more modern frameworks, etc.).

I think in 5 years from now, the JS community will be a lot more diverse and we'll see smaller frameworks (hopefully) out there. Something like React won't take 1.5 seconds to load in your app. I also forsee a lot of new frameworks focusing on VR and WebVR as the web evolves onto different platforms :)

These are all hopes as much as thoughts about the future 😜
