### ISSUE TITLE
Impostor Syndrome?

### ISSUE THREAD

**Issue by AllThingsSmitty** [una/ama#53]
Do you ever have bouts of self-doubt or impostor syndrome related to working in this industry? If so, how do you manage? What advice would you give others who are wondering "Can I do this? Am I good enough?"

**Comment by una** [comment]
In short: OMG YES ALL THE TIME OF COURSE 😆 I think imposter syndrome is totally normal and vital in pushing us to learn and be better.

I'm not great at everything, you're not great at everything, nobody is great at everything. But what we do have is a unique perspective to contribute.

In development, I think almost anything is possible with time and effort. But people often compare their learning struggle (aka their "works-in-process") with what they see out there (aka other people's final products), and then panic that they don't match up. OF COURSE THEY DON'T! What you're not seeing is the hours it took them to get there.

So I guess my advice would be to think about that perspective, and to really put the work in, giving yourself the time to get better, before comparing yourself to others and giving in.
