### ISSUE TITLE
Preparation for Front-end/UI Engineer Roles?

### ISSUE THREAD

**Issue by Siddharth11** [una/ama#54]
Hi Una!

What all areas should one focus on to get a Front-end/UI Engineer role at a company like DO? I don't have a CS background. I've been doing Front-end [for a while now](http://www.siddharthparmar.in/), and so far I've learned everything by practicing on [CodePen](http://codepen.io/Siddharth11/). How important is the knowledge of Data Structure and Algorithms for such roles?

**Comment by una** [comment]
You really don't need to know those things for UI Engineering, unless you're planning to apply to Google (and even so, you only need them to pass the interview). I'd focus on technologies you can use for every day work, primarily JavaScript, CSS architecture, and accessible HTML (Probably nothing new you havent heard before 😛)

Your Codepen demos are beautiful! Keep up the great work :)
