### ISSUE TITLE
a few questions about Toolsday

### ISSUE THREAD

**Issue by rockcoder23** [una/ama#55]
* Could you tell us how you and  Chris Dhanaraj run the Toolsday ?
* Can the Toolsday‘s manuscript be open source?
* what's your favarite podcast

**Comment by una** [comment]
Toolsday is pretty scrappy :P We just plan around a topic or technology, record a show, and post it the following week. Each of us records our own audio in Adobe Audition, and then Chris mixes it together. There's minimal editing.

We don't have any money to hire a company to pull the manuscript from the audio, but if anybody wants to do so, please be our guests.

My favorite podcast is Planet Money :) Its super interesting, short, and packed full of information!

**Comment by rockcoder23** [comment]
Thank you for your reply~
