### ISSUE TITLE
Hey, Una!

### ISSUE THREAD

**Issue by ghost** [una/ama#56]
Hey, Una! You've been super inspiring for me especially your attitude of shipping and being super welcoming in your projects (I loved contributing to CSSgram even though it was a small one!)

So! I was wondering ... would you like to be in my podcast? It's a tiny one that talks about how people got to where they are now and their day-to-day habits. We also just talk about life in general and being funny and doing whatever. :)

Two eps are currently up if ya wanna give it a lil listen! https://soundcloud.com/friendstalkfrontend

![](https://cloud.githubusercontent.com/assets/81969/21967284/dcadfa88-db51-11e6-928b-16ee196234d4.gif)

Thank you so much for reading!

**Comment by una** [comment]
That would be awesome! :) email me una.kravets@gmail.com
