### ISSUE TITLE
Best books to read in 2017

### ISSUE THREAD

**Issue by mmdsharifi** [una/ama#57]
Hi una!

I read your blog posts and fallow your personal goals repo, that's great! ... one of my goals is read many books in this year as front end developer, so witch is **top ten** books (technical, non-technical) for 2017? let me know!

**Comment by una** [comment]
Oh my gosh, I [read a lot](https://github.com/una/personal-goals/blob/master/ideas-and-misc/book-checklist.md)

Here are 13 favorites broken into categories (ugh so hard to pick favorites and 10 wasn't enough):

Fiction (all Sci FI, to be honest)
---
- Ready Player One -- Ernest Cline
- Dark Matter -- Blake Crouch
- Flowers for Algernon -- Daniel Keyes
- The Girl with All the Gifts -- M. R. Carey
- The Circle -- Dave Eggars
- The First Fifteen Lives of Harry August -- Catherine Webb

Non-fiction
---
- Born a Crime -- Trevor Noah
- Leaders Eat Last -- Simon Sinek
- Ghost in The Wires -- Kevin Mitnick
- Outliers -- Malcolm Gladwell

Web Development
---
- Weaving the Web -- Tim Berners-Lee
- Resilient Web Design -- Jeremy Keith
- CSS Secrets -- Lea Verou
